tasks:
  - name: Setup Environment
    init: |
      sudo apt-get update
      # Install Chrome with dependencies
      sudo apt-get install -y wget gnupg python3-pip \
          libxss1 libnss3 libasound2 libgbm1 libgtk-3-0
      
      # Install Chrome
      wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
      sudo apt-get update
      sudo apt-get install -y google-chrome-stable
      
      # Set up chromedriver
      sudo mkdir -p /usr/local/bin/chromedriver
      sudo ln -s /usr/bin/google-chrome-stable /usr/bin/chrome
      echo 'export PATH="/usr/local/bin/chromedriver:$PATH"' >> ~/.bashrc
      source ~/.bashrc
      
      # Python setup
      pip install --upgrade pip
      pip install -r requirements.txt

services:
  - name: mongodb
    image: mongo:6.0
    command: [--dbpath, /data/db, --bind_ip_all]
    ports:
      - 27017:27017
    volumes:
      - /workspace/mongo-data:/data/db

vscode:
  extensions:
    - ms-python.python
