tasks:
  - name: Setup Environment
    init: |
      sudo apt-get update
      # Install essential Chrome dependencies
      sudo apt-get install -y wget gnupg python3-pip \
          libxss1 libnss3 libasound2 libgbm1 libgtk-3-0
      
      # Install Chrome using official Google repository
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
      wget -qO - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      sudo apt-get update
      sudo apt-get install -y google-chrome-stable
      
      # Verify installation
      echo "Chrome version: $(google-chrome-stable --version)"
      
      # Install Python dependencies
      pip install --upgrade pip
      pip install -r requirements.txt

services:
  - name: mongodb
    image: mongo:6.0
    command: [--dbpath, /data/db, --bind_ip_all]
    ports:
      - 27017:27017
    volumes:
      - /workspace/mongo-data:/data/db

vscode:
  extensions:
    - ms-python.python
