tasks:
  - name: Setup Environment
    init: |
      # Update system and install dependencies
      sudo apt-get update
      sudo apt-get install -y \
          libnss3 \
          libnspr4 \
          libxss1 \
          libasound2 \
          libxtst6 \
          libgtk-3-0 \
          libgbm-dev \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libcups2 \
          libdrm2 \
          libatspi2.0-0 \
          libxcomposite1 \
          libxdamage1 \
          libxfixes3 \
          libxrandr2 \
          libxkbcommon0 \
          libpango-1.0-0 \
          libcairo2

      # Install Python dependencies
      pip install --upgrade pip
      pip install -r requirements.txt

      # Install Playwright browsers
      python -m playwright install chromium
      python -m playwright install-deps

services:
  - name: mongodb
    image: mongo:6.0
    command: [--dbpath, /data/db, --bind_ip_all]
    ports:
      - 27017:27017
    volumes:
      - /workspace/mongo-data:/data/db

vscode:
  extensions:
    - ms-python.python
    - ms-playwright.playwright
